# Generated by Django 5.2.1 on 2026-03-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('quoteNumber', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(default='DRAFT', max_length=50)),
                ('clientRef', models.JSONField(blank=True, null=True)),
                ('linkedDesign', models.JSONField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.JSONField(blank=True, default=dict)),
                ('discountAmount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxRate', models.DecimalField(decimal_places=4, default=0.16, max_digits=8)),
                ('taxAmount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('audit', models.JSONField(blank=True, default=dict)),
                ('extras', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('CAD_BOM', 'CAD_BOM'), ('MANUAL', 'MANUAL')], default='MANUAL', max_length=20)),
                ('traceability', models.JSONField(blank=True, null=True)),
                ('catalogRef', models.JSONField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('marginRate', models.DecimalField(decimal_places=4, default=0.2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('discount', models.JSONField(blank=True, default=dict)),
                ('discountAmount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('isReadOnlyFromCad', models.BooleanField(default=False)),
                ('isDesignLinked', models.BooleanField(default=False)),
                ('audit', models.JSONField(blank=True, default=dict)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineItems', to='quoter.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
