# Generated by Django 5.2.1 on 2026-03-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessorySpec',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('DERIVED', 'DERIVED'), ('EXPLICIT', 'EXPLICIT')], max_length=20)),
                ('scope', models.CharField(choices=[('RACK_LINE', 'RACK_LINE'), ('BAY', 'BAY'), ('LEVEL', 'LEVEL')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BeamSpec',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('lengthIn', models.FloatField()),
                ('capacityClass', models.CharField(max_length=50)),
                ('beamSeries', models.CharField(max_length=100)),
                ('connectorType', models.CharField(max_length=100)),
                ('verticalEnvelopeIn', models.FloatField()),
                ('profileHeightIn', models.FloatField()),
                ('compatibleUprightSeries', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ColumnEntity',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RACK_MODULE', 'RACK_MODULE'), ('RACK_LINE', 'RACK_LINE'), ('WALL', 'WALL'), ('COLUMN', 'COLUMN'), ('TEXT_NOTE', 'TEXT_NOTE')], default='COLUMN', max_length=20)),
                ('transform', models.JSONField(default=dict)),
                ('widthM', models.FloatField(default=0.3)),
                ('depthM', models.FloatField(default=0.3)),
                ('shape', models.CharField(choices=[('RECT', 'RECT'), ('ROUND', 'ROUND')], default='RECT', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DesignRevision',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('revisionNumber', models.PositiveIntegerField()),
                ('catalogVersion', models.CharField(max_length=120)),
                ('validationResults', models.JSONField(blank=True, default=dict)),
                ('bomSnapshot', models.JSONField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdAt', '-revisionNumber'],
            },
        ),
        migrations.CreateModel(
            name='FrameSpec',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('heightIn', models.FloatField()),
                ('depthIn', models.FloatField()),
                ('beamSeparationIn', models.FloatField()),
                ('gauge', models.CharField(max_length=50)),
                ('capacityClass', models.CharField(max_length=50)),
                ('uprightSeries', models.CharField(max_length=100)),
                ('compatibleConnectorTypes', models.JSONField(blank=True, default=list)),
                ('minimumTopClearanceIn', models.FloatField()),
                ('basePlateType', models.CharField(choices=[('STANDARD', 'STANDARD'), ('HEAVY_DUTY', 'HEAVY_DUTY')], default='STANDARD', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RackLineEntity',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RACK_MODULE', 'RACK_MODULE'), ('RACK_LINE', 'RACK_LINE'), ('WALL', 'WALL'), ('COLUMN', 'COLUMN'), ('TEXT_NOTE', 'TEXT_NOTE')], default='RACK_LINE', max_length=20)),
                ('transform', models.JSONField(default=dict)),
                ('domainId', models.CharField(max_length=120)),
                ('widthM', models.FloatField()),
                ('depthM', models.FloatField()),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RackModuleEntity',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RACK_MODULE', 'RACK_MODULE'), ('RACK_LINE', 'RACK_LINE'), ('WALL', 'WALL'), ('COLUMN', 'COLUMN'), ('TEXT_NOTE', 'TEXT_NOTE')], default='RACK_MODULE', max_length=20)),
                ('transform', models.JSONField(default=dict)),
                ('domainId', models.CharField(max_length=120)),
                ('widthM', models.FloatField()),
                ('depthM', models.FloatField()),
                ('bayCount', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TextNoteEntity',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RACK_MODULE', 'RACK_MODULE'), ('RACK_LINE', 'RACK_LINE'), ('WALL', 'WALL'), ('COLUMN', 'COLUMN'), ('TEXT_NOTE', 'TEXT_NOTE')], default='TEXT_NOTE', max_length=20)),
                ('transform', models.JSONField(default=dict)),
                ('text', models.TextField()),
                ('fontSizeM', models.FloatField(default=0.3)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WallEntity',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RACK_MODULE', 'RACK_MODULE'), ('RACK_LINE', 'RACK_LINE'), ('WALL', 'WALL'), ('COLUMN', 'COLUMN'), ('TEXT_NOTE', 'TEXT_NOTE')], default='WALL', max_length=20)),
                ('transform', models.JSONField(default=dict)),
                ('lengthM', models.FloatField()),
                ('thicknessM', models.FloatField(default=0.2)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('leftFrameIndex', models.PositiveIntegerField()),
                ('rightFrameIndex', models.PositiveIntegerField()),
                ('isBeamSpecCustomized', models.BooleanField(default=False)),
                ('accessoryIds', models.JSONField(blank=True, default=list)),
                ('beamSpec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bays', to='cad.beamspec')),
            ],
            options={
                'ordering': ['leftFrameIndex', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('targetLevelIndex', models.PositiveIntegerField(blank=True, null=True)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='cad.accessoryspec')),
                ('targetBay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targetedAccessories', to='cad.bay')),
                ('designRevision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='cad.designrevision')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RackLine',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('rowConfiguration', models.CharField(choices=[('SINGLE', 'SINGLE'), ('BACK_TO_BACK_2', 'BACK_TO_BACK_2'), ('BACK_TO_BACK_3', 'BACK_TO_BACK_3'), ('BACK_TO_BACK_4', 'BACK_TO_BACK_4')], default='SINGLE', max_length=20)),
                ('levelMode', models.CharField(choices=[('UNIFORM', 'UNIFORM'), ('VARIABLE', 'VARIABLE')], default='UNIFORM', max_length=20)),
                ('backToBackConfig', models.JSONField(blank=True, null=True)),
                ('totalBayCount', models.PositiveIntegerField(default=0)),
                ('totalFrameCount', models.PositiveIntegerField(default=0)),
                ('validationState', models.CharField(choices=[('INCOMPLETE', 'INCOMPLETE'), ('VALID', 'VALID'), ('VALID_WITH_WARNINGS', 'VALID_WITH_WARNINGS'), ('INVALID', 'INVALID')], default='INCOMPLETE', max_length=24)),
                ('accessoryIds', models.JSONField(blank=True, default=list)),
                ('designRevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rackLines', to='cad.designrevision')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('positionIndex', models.PositiveIntegerField()),
                ('isCustomSpec', models.BooleanField(default=False)),
                ('rowIndex', models.PositiveIntegerField(blank=True, null=True)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frames', to='cad.framespec')),
                ('rackLine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='cad.rackline')),
            ],
            options={
                'ordering': ['positionIndex', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RackModule',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('frameCount', models.PositiveIntegerField(default=0)),
                ('startFrameIndex', models.PositiveIntegerField()),
                ('endFrameIndex', models.PositiveIntegerField()),
                ('rowIndex', models.PositiveIntegerField(blank=True, null=True)),
                ('frameSpec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defaultModules', to='cad.framespec')),
                ('rackLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cad.rackline')),
            ],
            options={
                'ordering': ['startFrameIndex', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BeamLevel',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('levelIndex', models.PositiveIntegerField()),
                ('holeIndex', models.PositiveIntegerField()),
                ('elevationIn', models.FloatField(blank=True, default=0)),
                ('isBeamSpecCustomized', models.BooleanField(default=False)),
                ('bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='cad.bay')),
                ('beamSpec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beamLevels', to='cad.beamspec')),
                ('rackModule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levelUnion', to='cad.rackmodule')),
            ],
            options={
                'ordering': ['levelIndex', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bay',
            name='rackModule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='cad.rackmodule'),
        ),
        migrations.CreateModel(
            name='FrameOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localFrameIndex', models.PositiveIntegerField()),
                ('frameSpec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrideEntries', to='cad.framespec')),
                ('rackModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameOverrideEntries', to='cad.rackmodule')),
            ],
            options={
                'ordering': ['localFrameIndex', 'id'],
                'constraints': [models.UniqueConstraint(fields=('rackModule', 'localFrameIndex'), name='unique_frame_override_per_module_index')],
            },
        ),
    ]
